apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::800618366722:role/eksctl-brain-tasks-cluster-nodegro-NodeInstanceRole-h8wHTRwI7lJq
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::800618366722:role/service-role/codebuild-brain-tasks-app-build-service-role
      username: codebuild
      groups:
      - system:masters
